In [1]:
import numpy as np

In [5]:
#creating a 1D array
arr1 = np.array([1,2,3,4,5])

In [6]:
arr1

array([1, 2, 3, 4, 5])

In [8]:
print(type(arr1))

<class 'numpy.ndarray'>


In [9]:
arr1.shape

(5,)

In [12]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [15]:
arr3 = np.array([[1,2,3],[5,6,7]])
arr3

array([[1, 2, 3],
       [5, 6, 7]])

In [16]:
arr3.shape

(2, 3)

In [18]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
arr3 = np.array([[1,2,3],[5,6,7]])
print("Array: ",arr3)
print("Shape: ",arr3.shape)
print("Dimension: ", arr3.ndim)
print("Size: ", arr3.size)
print("Data Type: ", arr3.dtype)
print("Item Size in bytes: ",arr3.itemsize)

Array:  [[1 2 3]
 [5 6 7]]
Shape:  (2, 3)
Dimension:  2
Size:  6
Data Type:  int32
Item Size in bytes:  4


## Numpy vectorized operations

In [27]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print("Addition: ",arr1+arr2)
print("Subtraction: ", arr1-arr2)
print("multiplication: ",arr1*arr2)
print("division: ", arr1/arr2)

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
multiplication:  [ 10  40  90 160 250]
division:  [0.1 0.1 0.1 0.1 0.1]


## Universal Fuction

In [32]:
arr1 = np.array([2,3,4,5,6])
#square root
print(np.sqrt(arr1))

# exponential
print(np.exp(arr1))

#sine
print(np.sin(arr1))

# natural log
print(np.log(arr1))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


# Slicing and indexing

In [33]:
arr1= np.array([[1,2,3,4,5],[6,7,8,9,10],[10,11,12,13,14]])
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [10, 11, 12, 13, 14]])

In [35]:
arr1[0]

3

In [36]:
arr1[0,2]

3

In [37]:
arr1[1,4]

10

In [39]:
arr1[1:,2:]

array([[ 8,  9, 10],
       [12, 13, 14]])

In [40]:
arr1[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [42]:
arr1[0:2,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [43]:
arr1[1:,2:3]

array([[ 8],
       [12]])

In [47]:
## Modify array elements
arr1[0,0]=100
arr1

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 10,  11,  12,  13,  14]])

## Statistical concept
### Normalization

In [50]:
data = np.array([2,4,6,8,10])
mean = np.mean(data)
std = np.std(data)

normalized_data = (data-mean)/std
print("normalized_data",normalized_data)



normalized_data [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [51]:
print("mean: ",np.mean(data))
print("median: ",np.median(data))
print("std: ",np.std(data))
print("var: ",np.var(data))


mean:  6.0
median:  6.0
std:  2.8284271247461903
var:  8.0


## Logical operations

In [56]:
data= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True])

In [57]:
data[data>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [59]:
data[(data>5) & (data<12)]

array([ 6,  7,  8,  9, 10, 11])

In [62]:
data[(data>5) | (data>10)]

array([ 6,  7,  8,  9, 10, 11, 12, 13])